theme: jekyll-theme-primer
title: Flowers for Alda
description: A special collection

# GitHub Pages will use the root as source since we don't have a docs folder
source: .
destination: _site

# Exclude unnecessary files
exclude:
  - .git
  - .gitignore
  - README.md
  - LICENSE
