theme: jekyll-theme-primer
title: Flowers for Alda
description: A special collection

# Build from root directory
source: .
destination: ./_site

# Exclude unnecessary files
exclude:
  - .git
  - .gitignore
  - README.md
  - LICENSE
  - flowers-for-someone-main
